import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from shared.report_builder import AMAZON, OTTO, build_report


def _amazon_verdict(**overrides) -> dict:
    v = {
        "asin": "B0TESTASIN",
        "product_title": "Widget",
        "verdict": "LIKELY AUTHENTIC",
        "confidence": 0.7,
        "composite_score": 0.3,
        "risk_category": "LOW",
    }
    v.update(overrides)
    return v


def _otto_verdict(**overrides) -> dict:
    v = {
        "article_number": "123456789",
        "product_title": "Gerät",
        "verdict": "UNCERTAIN",
        "confidence": 0.5,
        "composite_score": 0.5,
        "risk_category": "MEDIUM",
    }
    v.update(overrides)
    return v


class ReportBuilderTests(unittest.TestCase):
    def test_confidence_rendered_as_percent_when_present(self):
        html = build_report(_amazon_verdict(confidence=0.7), AMAZON)
        self.assertIn("Confidence: <strong>70%</strong>", html)

    def test_missing_confidence_renders_em_dash_not_zero(self):
        v = _amazon_verdict()
        v.pop("confidence")
        html = build_report(v, AMAZON)
        self.assertIn("Confidence: <strong>—</strong>", html)
        self.assertNotIn("Confidence: <strong>0%</strong>", html)

    def test_invalid_confidence_type_renders_em_dash(self):
        html = build_report(_amazon_verdict(confidence="high"), AMAZON)
        self.assertIn("Confidence: <strong>—</strong>", html)

    def test_otto_uses_german_lang_and_article_label(self):
        html = build_report(_otto_verdict(), OTTO)
        self.assertIn('lang="de"', html)
        self.assertIn("Article: 123456789", html)
        self.assertIn("OTTO Counterfeit Report", html)

    def test_amazon_uses_english_lang_and_asin_label(self):
        html = build_report(_amazon_verdict(), AMAZON)
        self.assertIn('lang="en"', html)
        self.assertIn("ASIN: B0TESTASIN", html)

    def test_amazon_falls_back_to_actual_brand(self):
        v = _amazon_verdict(actual_brand="Acme")
        html = build_report(v, AMAZON)
        self.assertIn("Acme", html)

    def test_amazon_primary_seller_label(self):
        html = build_report(_amazon_verdict(primary_seller="Acme Corp"), AMAZON)
        self.assertIn("Primary Seller", html)
        self.assertIn("Acme Corp", html)

    def test_otto_seller_label_and_field(self):
        html = build_report(_otto_verdict(seller="Otto Händler"), OTTO)
        self.assertIn(">Seller<", html)
        self.assertIn("Otto Händler", html)

    def test_html_is_escaped_in_title(self):
        html = build_report(_amazon_verdict(product_title="<script>alert(1)</script>"), AMAZON)
        self.assertNotIn("<script>alert(1)</script>", html)
        self.assertIn("&lt;script&gt;", html)

    def test_risk_flags_rendered(self):
        v = _amazon_verdict(risk_flags=[{"flag": "FBM seller", "severity": "HIGH", "detail": "d"}])
        html = build_report(v, AMAZON)
        self.assertIn("FBM seller", html)
        self.assertIn("HIGH", html)

    def test_footer_distinguishes_platforms(self):
        amazon_html = build_report(_amazon_verdict(), AMAZON)
        otto_html = build_report(_otto_verdict(), OTTO)
        self.assertIn("Generated by Fake Product Detector ", amazon_html)
        self.assertIn("Generated by Fake Product Detector (OTTO)", otto_html)


if __name__ == "__main__":
    unittest.main()
